/**
 * InsideSalesLeads - Dashboard panel for inside sales lead display
 *
 * Shows qualified development leads generated by the Inside Sales Bot,
 * including developer name, market, lead score, confidence, and timestamp.
 *
 * Polls /api/sales-leads every 30 seconds for updates.
 */

import React, { useState, useEffect, useCallback } from 'react';

// ---- Types ----

interface SalesLead {
  id: string;
  developer: string;
  city: string;
  state: string;
  score: number;
  confidence: number;
  source_signal: string;
  created_at: string;
}

// ---- Constants ----

const POLL_INTERVAL_MS = 30_000;

// ---- Helpers ----

function scoreColor(score: number): string {
  if (score >= 90) return '#00ff88';
  if (score >= 80) return '#00ccff';
  if (score >= 70) return '#ffaa00';
  return '#888888';
}

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
}

// ---- Component ----

const InsideSalesLeads: React.FC = () => {
  const [leads, setLeads] = useState<SalesLead[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchLeads = useCallback(async () => {
    try {
      const res = await fetch('/api/sales-leads?limit=50');
      if (res.ok) {
        const data = await res.json();
        setLeads(data.leads || []);
      }
    } catch (err) {
      console.error('[InsideSalesLeads] Fetch error:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchLeads();
    const interval = setInterval(fetchLeads, POLL_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [fetchLeads]);

  if (loading) {
    return (
      <div style={{ padding: '1rem', color: '#888' }}>
        Loading inside sales leads...
      </div>
    );
  }

  if (leads.length === 0) {
    return (
      <div style={{ padding: '1rem', color: '#888' }}>
        No qualified leads detected yet.
      </div>
    );
  }

  return (
    <div style={{ padding: '1rem' }}>
      <h2 style={{ marginBottom: '1rem', color: '#00ff88', fontSize: '1.2rem' }}>
        Inside Sales Leads
      </h2>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.9rem' }}>
        <thead>
          <tr style={{ borderBottom: '1px solid #333', color: '#aaa', textAlign: 'left' }}>
            <th style={{ padding: '0.5rem' }}>Developer</th>
            <th style={{ padding: '0.5rem' }}>Market</th>
            <th style={{ padding: '0.5rem' }}>Score</th>
            <th style={{ padding: '0.5rem' }}>Confidence</th>
            <th style={{ padding: '0.5rem' }}>Detected</th>
          </tr>
        </thead>
        <tbody>
          {leads.map((lead) => (
            <tr key={lead.id} style={{ borderBottom: '1px solid #222' }}>
              <td style={{ padding: '0.5rem', color: '#fff' }}>{lead.developer}</td>
              <td style={{ padding: '0.5rem', color: '#ccc' }}>
                {lead.city}, {lead.state}
              </td>
              <td style={{ padding: '0.5rem', color: scoreColor(lead.score), fontWeight: 'bold' }}>
                {lead.score}
              </td>
              <td style={{ padding: '0.5rem', color: '#aaa' }}>{lead.confidence}%</td>
              <td style={{ padding: '0.5rem', color: '#666' }}>{timeAgo(lead.created_at)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default InsideSalesLeads;
